lets see if this works

diff --git a/.github/workflows/clang-format-test.yml b/.github/workflows/clang-format-test.yml
--- a/.github/workflows/clang-format-test.yml
+++ b/.github/workflows/clang-format-test.yml
@@ -17,11 +17,9 @@ jobs:
     - name: Run clang-format
       run: |
         SOURCE_DIR="src"
-        FORMAT_ERRORS=0
         find "$SOURCE_DIR" -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.tpp" \) | while read -r FILENAME; do
           if ! clang-format -output-replacements-xml "$FILENAME" | grep -q "<replacement "; then
-            echo "$FILENAME is not formatted correctly"
-            FORMAT_ERRORS=-1
+            echo "::error file=$FILENAME::File is not formatted correctly"
+            exit 1
           fi
         done
-        exit $FORMAT_ERRORS
